CREATE TABLE [dbo].[PLANNING]
(
	[Id] INT NOT NULL PRIMARY KEY, 
    [USER ID] VARCHAR(10) NOT NULL, 
    [STARTING POINT] INT NOT NULL DEFAULT 0, 
    [DESTINATION] INT NOT NULL DEFAULT 0, 
    [FROM DATE] DATE NOT NULL, 
    [TO DATE] DATE NOT NULL, 
    [MODE] INT NOT NULL
)
